// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbQHaLzLxF_1CwYmxk_ow0GMtQdUgjKE',
    appId: '1:147772349621:web:6e7766b6880263b1b572fc',
    messagingSenderId: '147772349621',
    projectId: 'netloop-c9026',
    authDomain: 'netloop-c9026.firebaseapp.com',
    storageBucket: 'netloop-c9026.firebasestorage.app',
    measurementId: 'G-CD25QKGXC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCwmTkbJGxHqn8OA1lbel3lT2_b4rKms',
    appId: '1:147772349621:android:ecffd9f64caadfcbb572fc',
    messagingSenderId: '147772349621',
    projectId: 'netloop-c9026',
    storageBucket: 'netloop-c9026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpe6yBYAU98YPhqw8Bm4QXAVtrKyOpHxU',
    appId: '1:147772349621:ios:8ed911a9777da042b572fc',
    messagingSenderId: '147772349621',
    projectId: 'netloop-c9026',
    storageBucket: 'netloop-c9026.firebasestorage.app',
    iosBundleId: 'com.example.netloop',
  );
}
